apiVersion: v1
kind: Secret
metadata:
  name: nayeli-08-secret
  namespace: nayeli-08-namespace
type: Opaque
data:
  DATABASE_NAME: bm9zcWw=
  DATABASE_URI: bW9uZ29kYitzcnY6Ly91c3VhcmlvOnBhc3NAc2Vydmlkb3I=