# kubectl apply -f mathias-delacruz-06-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: mathias-delacruz-06-secret
  namespace: mathias-delacruz-06-namespace
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9tYXRoaWFzZGxjMzAxMl9kYl91c2VyOjFlQ3k2WHNhQU45RTVJYjJAY2x1c3RlcjAuc3ZwbmtpdS5tb25nb2RiLm5ldC9hbHRhdmlzdGE/YXBwTmFtZT1DbHVzdGVyMA==   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode